services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  airflow-webserver:
    image: airflow-server
    command: bash -c "airflow db init && airflow users create --role Admin --username airflow --email airflow --firstname airflow --lastname airflow --password airflow 2>/dev/null; airflow webserver"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow/src:/opt/airflow
    volumes:
      - ${PWD}/dags:/opt/airflow/dags
      - ${PWD}/logs:/opt/airflow/logs
      - ${PWD}/plugins:/opt/airflow/plugins
      - ${PWD}/include:/opt/airflow/include
      - ${PWD}/src:/opt/airflow/src
      - ${PWD}//opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  airflow-scheduler:
    image: airflow-server
    command: airflow scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow/src:/opt/airflow
    volumes:
      - ${PWD}/dags:/opt/airflow/dags
      - ${PWD}/logs:/opt/airflow/logs
      - ${PWD}/plugins:/opt/airflow/plugins
      - ${PWD}/include:/opt/airflow/include
      - ${PWD}/src:/opt/airflow/src
      - ${PWD}//opt/airflow/data
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-db-volume:
